# azure-pipelines.yml
trigger:
  branches:
    include:
      - main # Trigger the pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest' # Use an Ubuntu agent to run the pipeline

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x' # Install .NET SDK version 6.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore # Restore NuGet packages
    dotnet build --configuration Release # Build the project
  displayName: 'Restore and Build'

- script: |
    dotnet test --configuration Release # Run unit tests
  displayName: 'Run Tests'

